
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ElectronicProtocolStartLine.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CT_Сustomers
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CT_Сustomers()
    {

        this.Contract_LOT = new HashSet<Contract_LOT>();

    }


    public int ID { get; set; }

    public string СustomerName { get; set; }

    public string ShortName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contract_LOT> Contract_LOT { get; set; }

}

}
