
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ElectronicProtocolStartLine.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EP_Monitoring
{

    public int id { get; set; }

    public string Line { get; set; }

    public string ProgrammName { get; set; }

    public Nullable<int> MaxModules { get; set; }

}

}
