//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicProtocolStartLine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUJI
    {
        public int ID { get; set; }
        public string PGName { get; set; }
        public Nullable<short> Modules { get; set; }
        public string Line { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
